### ISSUE TITLE
Can Manalyze run in WinXP?

### ISSUE THREAD

**Issue by hi-T0day** [JusticeRage/Manalyze#14]
I found that Manalyze can run in Win7. But it did not work in WinXP. 
Is it true?

**Comment by JusticeRage** [comment]
Partly.
It's true that the binary I generated probably doesn't run on XP because I didn't have the XP compatibility libraries installed on my development machine. On the other hand, there is no reason why the code itself wouldn't function on that OS, so if you build the program from source, I don't think you'll have any issue getting it to run on XP.
